name: Branch Main Build

on:
  push:
    branches:
      - main
    paths:
      - '**.csproj'
      - '**.razor'
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
  
      - name: Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Install dependencies
        run: nuget restore TgDownloader.sln

      - name: Build app for Release Any CPU
        run: msbuild TgDownloader.sln -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="Any CPU"
        
      - name: Package artifacts
        run: |
          # 打包构建的文件
          tar czf my-app.tar.gz ./Clients
          
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./my-app.tar.gz
          asset_name: my-app.tar.gz
          asset_content_type: application/gzip
